run-name: PokemonCompagnon CI

on:
  push:
    branch:
      - master
      - develop
      - 11-automate
  pull_request:
    branches:
      - master
      - develop

jobs:
  unit-test:
    runs-on: ubuntu-latest
    container: kelvinlawson/android-studio

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: set up JDK 1.8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8

      # Execute unit tests
      - name: Unit Test
        run: ./gradlew test

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: run Android Test Report
